language:
  - node_js

node_js:
  - "stable"

cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

install:
  - npm ci

script:
  - npm test
  - $(npm bin)/cypress run --record

notifications:
  slack:
    rooms:
      - tna-digital:C2GnodnLsxhwwGvr0xAcajzc#code-builds